name: CustomBans
main: me.itzrex.cbans.CustomBans
version: 0.8
description: Custom plugin for bans players.
author: itzRex
load: STARTUP
commands:
    ban:
    unban:
    custombans:
        aliases: [cbans]
    kick:
    mute:
    unmute:
    warn: