name: CustomBans
main: me.itzrex.cbans.CustomBans
version: 0.3
description: Custom plugin for bans players.
author: itzRex
load: STARTUP
commands:
    ban:
    unban:
    custombans:
        aliases: [cbans]
    checkban:
    tempban:
    kick:
    mute:
    unmute:
    tempmute:
    baninv: